export const DEFAULT_SNAPSHOT_BUFFER_CONFIG = Object.freeze({
  maxStateBuffer: 90,
  initialInterpDelayMs: 100,
  minInterpDelayMs: 66,
  maxInterpDelayMs: 160,
  snapIntervalMs: 1000 / 30,
  maxSpacingMs: 500,
  lateSnapshotThresholdMs: 140,
  largePositionDeltaPx: 90,
  spacingEmaAlpha: 0.12,
  enableAdaptiveDelay: true,
  enableClockCorrection: false,
  enableBacklogCatchup: true,
  extrapolationLimitMs: 1000,
});
